### ISSUE TITLE
String#blank? differs from ActiveSupport

### ISSUE THREAD

**Issue by johanlunds** [kristianmandrup/sugar-high#1]
sugar-high:

```
class String
  def blank?
    self.empty?
  end
  # ...
end
```

activesupport:

```
class String #:nodoc:
  def blank?
    self !~ /\S/
  end
end
```

String with contents `"\n  \n"` will give different results.

I depend on `roles_active_record` and `roles_generic` which I like. However for now I'll refactor to do without them. I'd like to put them in again if the the dependency on `sugar-high` could be removed. Seems like a bad idea to mix two extension/monkeypatching libraries, or what do you say?

**Comment by johanlunds** [comment]
`roles_active_record` depends on a lot of gems, see my Gemfile.lock diff when removing it: https://gist.github.com/847144

**Comment by kristianmandrup** [comment]
Sorry, I wasn't aware of this! I will fix it right away!
