### ISSUE TITLE
Array#none? is a collision with stdlib

### ISSUE THREAD

**Issue by sj26** [kristianmandrup/sugar-high#11]
http://ruby-doc.org/core-1.9.3/Enumerable.html#method-i-none-3F

This breaks many things in other projects and gems.

**Comment by kristianmandrup** [comment]
Sorry, I will fix that ASAP.

**Comment by kristianmandrup** [comment]
Should be fixed in release 0.6.3 I just made.

**Comment by sj26** [comment]
Cheers! This should fix problems with rspec. :-)
