### ISSUE TITLE
file_mutate.rb requires removed file 'extras'

### ISSUE THREAD

**Issue by gavinheavyside** [kristianmandrup/sugar-high#2]
I've just tried to use cream, and it pulled in sugar-high 0.4.4. When I ran the devise:config generator it raised an exception because file_mutate.rb still requires 'extras', which has been removed.

Including `gem 'sugar-high', '<= 0.4.2'` in my Gemfile is a workaround.

```
$ rails g devise:config
/Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require': no such file to load -- sugar-high/file_mutate/extras (LoadError)
from /Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
from /Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
from /Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
from /Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
from /Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
from /Users/gavin/.rvm/gems/ruby-1.9.2-p180-fastrequire/gems/sugar-high-0.4.4/lib/sugar-high/file_mutate.rb:15:in `<top (required)>'
```

**Comment by kristianmandrup** [comment]
Hi @hgavin, thanks for the update! I just fixed the bug in sugar-high, strange that I didn't see it before!
Now the whole file_mutate spec suite runs without failure! Pushed a 0.4.4.1 release. Cheers!

You might wanna check out my latest _troles_ project. 

https://github.com/kristianmandrup/troles

I'm working hard to rework Cream from the ground up, hoping to give a talk about it at the next RubyConf.
It will be called "dancing tango with troles"...
