### ISSUE TITLE
File Mutate Project

### ISSUE THREAD

**Issue by trans** [kristianmandrup/sugar-high#6]
The File mutation system looks very interesting (though I  don't fully understand it and it's uses yet). But it seems to me it might make a very good project on it's own.

**Comment by kristianmandrup** [comment]
Yeah, good point! Also check out the #class_ext we just made some nice additions today! Feel very welcome to extract the file and file_mutation API in its own project, if you just give me some credits ;) oh! it should now be backwards compatible with how it worked before (if you had any issues with some of my other gems that rely on this functionality)

**Comment by kristianmandrup** [comment]
I have extracted and created a _file_mutate_ project like you suggested ;)

https://github.com/kristianmandrup/file_mutate

**Comment by trans** [comment]
Awesome. When I get some time I'll check it out in more detail, and see if I can help out.
